### ISSUE TITLE
ipv6 bug in alpine

### ISSUE THREAD

**Issue by acidtib** [delef/maxminddb.cr#12]
the application won't build on the alpine docker image `crystallang/crystal:0.35.1-alpine`

https://github.com/delef/maxminddb.cr/blob/6ed46a18e8631010004692d9e67eb96fe1cbe3a3/src/maxminddb/ip_address.cr#L42

![m](https://user-images.githubusercontent.com/1427640/105619227-99715980-5dad-11eb-8a30-06ba2a9c71e7.PNG)

**Comment by delef** [comment]
Thank you! I will try to release the fix soon.

**Comment by delef** [comment]
@arubinofaux Can you try the current master?
