### ISSUE TITLE
Use Crystal 0.34 Datum feature instead of MaxMindDB::Any?

### ISSUE THREAD

**Issue by 636f7374** [delef/maxminddb.cr#8]
# Summary

* Crystal introduced a [Datum feature](https://github.com/crystal-lang/crystal/pull/8847) in version 0.34, which provides support for `Log`, and can also be used in other places.
* I have used it in [my branch repository](https://github.com/64726f70/maxminddb.cr) and it works very well.

## Improve

* Reuqire Datum

```crystal
require "crystal/datum"
```

*  MaxMindDB::Any

```crystal
module MaxMindDB
  struct Any
    Crystal.datum types: {nil: Nil, bool: Bool, s: String, i: Int32, u16: UInt16, u32: UInt32, u64: UInt64, u128: UInt128, f: Float32, f64: Float64, aany: Array(Any)}, hash_key_type: String, immutable: false

    def initialize(@raw : Type)
    end

    def found?
      size > 0_i32
    end

    def empty?
      !found?
    end

    def to_json(json : ::JSON::Builder)
      raw.to_json json
    end

    def as_i : Int32
      raw.as(Int).to_i
    end
  end
end
```

## References

* [crystal / Log Module](https://github.com/crystal-lang/crystal/pull/8847)
* [crystal / datum.cr](https://github.com/bcardiff/crystal/blob/fca877b04fb92726c58b1dfa0947fbc31683b3de/src/crystal/datum.cr)

**Comment by delef** [comment]
Thanks 🙂

**Comment by 636f7374** [comment]
:)
